module.exports = {
	eventID: '332',
	participants: [
		{
			team: [
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
			],
			idea: {
				title: 'qqqqqq',
				description: 'qqqqqq',
				problem: 'qqqqqq',
				attracting: 'qqqqqq',
				resources: 'qqqqqq',
				steps: 'qqqqqq',
				audience: 'qqqqqq',
			},
		},

		{
			team: [
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
			],
			idea: {
				title: 'qqqqqq',
				description: 'qqqqqq',
				problem: 'qqqqqq',
				attracting: 'qqqqqq',
				resources: 'qqqqqq',
				steps: 'qqqqqq',
				audience: 'qqqqqq',
			},
		},

		{
			team: [
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
			],
			idea: {
				title: 'qqqqqq',
				description: 'qqqqqq',
				problem: 'qqqqqq',
				attracting: 'qqqqqq',
				resources: 'qqqqqq',
				steps: 'qqqqqq',
				audience: 'qqqqqq',
			},
		},

		{
			team: [
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
				{
					name: 'qqqqqq',
					surname: '',
					telephone: 'qqqqqq',
					vkID: 'qqqqqq',
					grade: 'qqqqqq',
				},
			],
			idea: {
				title: 'qqqqqq',
				description: 'qqqqqq',
				problem: 'qqqqqq',
				attracting: 'qqqqqq',
				resources: 'qqqqqq',
				steps: 'qqqqqq',
				audience: 'qqqqqq',
			},
		},
	],
};
